name: 'energy_transition_tracker'
version: '1.0.0'
config-version: 2

profile: 'energy_transition_tracker'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  energy_transition_tracker:
    +materialized: view
