energy_transition_tracker:
  outputs:
    dev:
      type: duckdb
      path: '/Users/jorgecontreras/Desktop/projects/energy-transition-tracker/energy_tracker.duckdb'
      threads: 4
      settings:
        s3_region: "us-east-1"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_KEY') }}"

    prod:
      type: duckdb
      path: 'energy_tracker_prod.duckdb'
      threads: 4

  target: dev
